### PR TITLE
Trigger production deployments on pushes to prod branch

### PR DESCRIPTION
**Pull request by jgmize**
## Description

Per discussion in #websites channel in slack let's trigger production deployments on push to the `prod` branch.

### CODE REVIEW

**Comment by metadave** [comment]
it would be nice to have a few words in the readme about how to deploy to prod: 
ex. https://github.com/mozilla/irlpodcast#pushing-to-production

**Comment by glogiotatidis** [comment]
> it would be nice to have a few words in the readme about how to deploy to prod:
> ex. https://github.com/mozilla/irlpodcast#pushing-to-production

The [mana page](https://mana.mozilla.org/wiki/display/EN/careers.mozilla.org) is up to date and has instructions, albeit maybe not detailed. I will also add a link to the pipeline in the readme.

**Comment by glogiotatidis** [comment]
Merging this to test the trigger. Will also add instructions

**Comment by glogiotatidis** [comment]
Also added instructions https://github.com/mozmeao/lumbergh/commit/b6c2fa49fc6ab177ccaabb7b32bf01a3c4ad2dae

**Comment by glogiotatidis** [comment]
Had to set `prod` branch to be `protected` in Gitlab for the Creds to be applied in the environment. And also commit https://github.com/mozmeao/lumbergh/commit/1284e690b751fa0ec52737ab16ebce25335237d3 to make robots work

Everything seems to work now. Thanks everyone!

btw @jgmize do you mind not pushing branches to the main repos and instead do it to your fork? It pollutes the namespace in both github and gitlab

**Pull request merged**
