### PR TITLE
Added two fast company logos too footer. Resized as small as I could …

### LINKED ISSUE #393: Adding Fast Co Most Innovative Company Logos to Mozilla Career site
Please add in Fast Co #3 (security) and #49 (overall) logos to careers.mozilla.org top right corner.

Logo usage guide + logo:

[Fast Company's Most Innovative Companies logo usage guide.pdf](https://github.com/mozmeao/lumbergh/files/2886398/Fast.Company.s.Most.Innovative.Companies.logo.usage.guide.pdf)

[fastcompanylogoscustomizedfor3insecurityand49in.zip](https://github.com/mozmeao/lumbergh/files/2886399/fastcompanylogoscustomizedfor3insecurityand49in.zip)

### PR DESCRIPTION
**Pull request by bensternthal**
…while keeping this legible.

Closes #393

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Can you please compress the images? I like to use https://tinypng.com/

**Comment by bensternthal** [comment]
Good catch! Updated.

**Comment by glogiotatidis** [comment]
Is this good to go @bensternthal @stephaniehobson ?

**Comment by bensternthal** [comment]
@stephaniehobson can you give me a thumbs up or if you want any other tweaks or changes just lemme know? As always much thanks.

**Comment by stephaniehobson** [comment]
R+ from a code perspective. I did not spin it up and test it runs.

I don't have write access to this repo either so I can't merge.

**Comment by bensternthal** [comment]
@stephaniehobson you can view a demo at

https://deploy-preview-394--mozilla-careers-stage.netlify.com/

Beyond code i'd like a sanity check on how this looks. I tried making the logos smaller but the bottom text got jaggy.

**Comment by stephaniehobson** [comment]
Yeah they're pretty big. Do you think we could edit them or is that against their rules?

wide

I'm not surprised that they're janky. They are PNG files but full of JPEG artifacts. Shrinking them with CSS is working pretty well for me though if you wanted to "cheat". Around 170px looks good to me.

The placement is awkward but we'd need to do some design work to make it less awkward. I think you've found the best spot for now.

Also, is there anything we should link them to?

**Comment by bensternthal** [comment]
- No links, I did ask.
- We are not allowed to adjust the logos :(

**Comment by stephaniehobson** [comment]
I think it's good then unless you want to shrink them with CSS 👍

**Comment by bensternthal** [comment]
Smaller looks better. Shrunk via css.

**Pull request merged**
