### PR TITLE
[fix #347] Update University page

### LINKED ISSUE #347: Update University page
Description: The University page on careers.mozilla.org needs to be updated to correspond to the intern hiring process that is starting Monday, Oct 15th.

[Copy doc](https://docs.google.com/document/d/1Hv57PnJwaHXm4-2YC8BHIa7BfJg6LUmMX14_l7eEhMo/edit)

### PR DESCRIPTION
**Pull request by craigcook**
Updates various bits of copy on the University page as well as the intern videos (which were really old).

@stephaniehobson can you review?

### CODE REVIEW

**Comment by stephaniehobson** [comment]
The new images need to be compressed.

Not sure how much time you have to work on this but I would be tempted to kill the stickiness of the "you will" section now that it is half its old height.

And there is a pre-existing bug with how that section heading becomes sticky. It jumps down for some reason (I'm guessing there was some attempt to deal with the sticky header that went wrong, all the stuff that depends on the height of the sticky header is... off):

screen shot 2018-10-19 at 1 33 57 pm

screen shot 2018-10-19 at 1 33 39 pm

**Comment by stephaniehobson** [comment]
You need to remove all references to `videoInternsSrcOgv` now that isn't not defined anymore.

**Comment by stephaniehobson** [comment]
I think the weird jump-down/too much padding is added to sticky subheadings is a result of the sticky menu shrinking in size a few years ago. There's about 6 different numbers that need to be updated to fix it. It's a shame the original developer didn't use a pre-processor... oh wait, that's me.

**Comment by stephaniehobson** [comment]
R+ 👩‍🎓 

@glogiotatidis Can you merge and push please?

**Comment by glogiotatidis** [comment]
In production! Thank you both! :cake:

**Pull request merged**
