### PR TITLE
Remove top level internships menu item

### PR DESCRIPTION
**Pull request by helfi92**
Relates to https://github.com/mozmeao/lumbergh/issues/607.

My understanding is that Mozilla is suspending the internship program until further notice. Once the program is back, this PR could be reverted.

### CODE REVIEW

**Comment by ccooper** [comment]
@dianel Are you OK with us removing the Internships menu until Mozilla figures out what it's doing about interns?

**Comment by dianel** [comment]
hi all - yes lets hide the page for now (not delete it but hide it) - hope that's possible?

**Comment by ccooper** [comment]
@dianel Are you OK with us removing the Internships menu until Mozilla figures out what it's doing about interns?

> hi all - yes lets hide the page for now (not delete it but hide it) - hope that's possible?

Yep, the patch just removes the link, but the page will still exist.

**Review by ccooper — APPROVED** [review]
@dianel has signed off on this. Patch looks good.

**Pull request merged**
