### PR TITLE
Remove university events

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by pmac** [comment]
Also can I say that I'm a huge fan of the Netlify checks and integration! This is the first time I've seen all of them in action and having a deployment for this PR (you can get to via the "Pages changed" details) is so great 🥇

**Comment by metadave** [comment]
:+1:

**Comment by glogiotatidis** [comment]
> One suggestion would be to add a 40px solid bottom border on `#testimonials` to provide a visual break between the headshots and the rather busy gallery below. Happy to file a follow-up PR with that change.

Filed #374 for this

**Comment by glogiotatidis** [comment]
Thanks all!

**Pull request merged**
