### PR TITLE
[fix #374] Add visual break under university headshots.

### LINKED ISSUE #374: Add visual break between headshots and gallery in university page
From @jpetto in https://github.com/mozmeao/lumbergh/pull/373#pullrequestreview-196148119

>One suggestion would be to add a 40px solid bottom border on #testimonials to provide a visual break between the headshots and the rather busy gallery below. Happy to file a follow-up PR with that change.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by pmac** [comment]
This should have been based on the `static` branch, right?

**Comment by jpetto** [comment]
D'oh. Yep. 🤦‍♂️

**Comment by glogiotatidis** [comment]
Netlify tests fail b/c this needs a rebase on `static`. Tested locally and works fine

**Comment by glogiotatidis** [comment]
Thanks!

**Pull request merged**
